### ISSUE TITLE
Example Implementations復現不了

### ISSUE THREAD

**Issue by waynehacking8** [appier-research/streambench-final-project#4]
在WSL下command:
python -m examples.zeroshot --bench_name classification_public --model_name "Qwen/Qwen2.5-7B-Instruct" --device cuda --output_path /tmp/output.csv
和
python -m examples.self_streamicl --bench_name  classification_public --model_name "Qwen/Qwen2.5-7B-Instruct" --device cuda --output_path /tmp/output.csv

測試了大概100多個sample，zeroshot還比self_streamicl好，且大概到100多個sample後self_streamicl的instances數量增加後會越來越卡，不知道是RAG機制設定還是怎樣，把VRAM直接吃滿，zeroshot大概是擲硬幣的機率。

同組的也是:
zeroshot 在 ~43% accuracy 浮動 (step > 1000) 正常

streamicl 則是只有 ~20% accuracy，但在 step 31 時就因 runtime error 停了 (大概是一樣 VRAM 吃太多的問題？)

請問是我們下指令的方法錯了嗎?

**Comment by Brian-Ckwu** [comment]
同學你好，我是 Appier 的 Research Scientist 吳承光，這邊回答你的問題：

因為 Self-StreamICL 是利用 RAG 的 baseline method，隨著 memory 的內容越來越多，表現才會越來越進步，因此前面的表現是有可能落後 zero-shot 的，這也是同學們可以改善的方向：

<img width="331" alt="image" src="https://github.com/user-attachments/assets/9e1338d0-cb75-4011-8330-20edb78786f5">

上圖是用你的 command 在 Google Colab 復現的結果，由於使用 Free Colab，所以使用 --use_8bit 的版本節省記憶體用量，但其他指令是一模一樣的。可以發現大約到 700-th time step 時，Self-StreamICL 的表現才會超越 zero-shot，而最後的表現是有復現成功的 (51.375% vs. 44.174%)。

另外，因為這個醫療診斷任務是 49 分類，所以隨機的 performance 是 1/49 ~ 2.04%，而不是丟硬幣。

註：目前有新增 wandb 的功能在 main branch，歡迎使用。

* Colab 連結：https://colab.research.google.com/drive/1lSofAgZ_t_R60V_8VMv1Vde1L4A8MbzX?usp=sharing

**Comment by waynehacking8** [comment]
great thx
